# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAcWQMBZnyGO6i-Ar0-fcQjjZJBpHOtX
"""

# app.py
import streamlit as st
import pandas as pd
import numpy as np
import re
import io

import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

import plotly.graph_objects as go
import plotly.express as px

# ------------------------------
# Carregamento do arquivo Parquet
# ------------------------------
PARQUET_PATH = "consolidado.parquet"

@st.cache_data(show_spinner=False)
def carregar_parquet_local(caminho):
    try:
        df = pd.read_parquet(caminho)
        return df
    except Exception as e:
        st.error(f"Erro ao carregar Parquet: {e}")
        st.stop()

rede = carregar_parquet_local(PARQUET_PATH)

# ------------------------------
# Função de limpeza de moeda
# ------------------------------
def limpar_moeda(valor):
    if pd.isna(valor):
        return 0.0
    if isinstance(valor, (int, float, np.number)):
        return valor
    if isinstance(valor, str):
        v = valor.strip()
        if v in ("-", ""):
            return 0.0
        v = v.replace("R$", "").replace("r$", "").strip()
        v = re.sub(r"\.(?=\d{3},)", "", v)
        v = v.replace(",", ".")
        try:
            return float(v)
        except:
            return 0.0
    return 0.0

colunas_para_converter = [
    'Real', 'Meta Mês', 'Ticket Médio',
    'Novo', 'Refin', 'PORT + Refin da Port >=1,85',
    'Refin da Port < 1,85', 'Rep. Legal', 'META AUMENTO MARGEM'
]

for col in colunas_para_converter:
    if col in rede.columns and rede[col].dtype == object:
        rede[col] = rede[col].apply(limpar_moeda)

if 'Data' in rede.columns:
    rede['Data'] = pd.to_datetime(rede['Data'], errors='coerce')

def adicionar_dias(df):
    df = df.copy()
    df['ano_mes'] = df['Data'].dt.to_period('M')
    contagem = df.groupby(['Nome_Loja', 'ano_mes']).size().rename('DIAS')
    df = df.join(contagem, on=['Nome_Loja', 'ano_mes'])
    return df.drop(columns=['ano_mes'])

def preencher_meta_mes(df):
    df = df.copy()
    df['ano_mes'] = df['Data'].dt.to_period('M')
    df['Meta Mês'] = (
        df['Meta Mês'].replace(0, pd.NA)
        .groupby([df['Nome_Loja'], df['ano_mes']])
        .transform(lambda x: x.bfill())
        .fillna(0)
    )
    return df.drop(columns=['ano_mes'])

def calcular_variacao(df):
    df = df.copy()
    df['ano_mes'] = df['Data'].dt.to_period('M')
    df = df.sort_values(['Nome_Loja', 'ano_mes', 'Data'])

    def variacao(x):
        v = x - x.shift(1)
        v.iloc[0] = x.iloc[0]
        return v

    df['Real_Variacao'] = df.groupby(['Nome_Loja', 'ano_mes'])['Real'].transform(variacao)
    return df.drop(columns=['ano_mes'])

def calcular_meta_dia(df):
    df = df.copy()
    df['Meta Dia'] = df['Meta Mês'] / df['DIAS']
    return df

rede = adicionar_dias(rede)
rede = preencher_meta_mes(rede)
rede = calcular_variacao(rede)
rede = calcular_meta_dia(rede)

# ------------------------------------------------------
# INÍCIO — TÍTULO PRINCIPAL
# ------------------------------------------------------
st.title("Desempenho Comercial")

paginas = ["Produção", "Metas"]
pagina = st.selectbox("Selecione a página:", paginas)

# ------------------------------------------------------
# FUNÇÕES COMPARTILHADAS
# ------------------------------------------------------
def format_large_numbers(value):
    if value is None or pd.isna(value):
        return ""
    return f"R$ {value:,.0f}".replace(",", ".")

def filtrar_df(rede, produto, regional, coordenador, loja, mes, ano):
    df_f = rede.copy()

    if produto != "Todos":
        df_f = df_f[df_f["Produto"] == produto]
    if regional != "Todas":
        df_f = df_f[df_f["Regional"] == regional]
    if coordenador != "Todos":
        df_f = df_f[df_f["Coordenador"] == coordenador]
    if loja != "Todas":
        df_f = df_f[df_f["Nome_Loja"] == loja]

    df_f = df_f[
        (df_f["Data"].dt.year == int(ano)) &
        (df_f["Data"].dt.month == int(mes))
    ]

    return df_f

def calcular_acumulados(df):
    df_grouped = (
        df.groupby("Data", as_index=False)
        .agg({
            "DIAS": "sum",
            "Real_Variacao": "sum",
            "Meta Dia": "sum"
        })
        .sort_values("Data")
        .reset_index(drop=True)
    )

    df_grouped["REAL_ACUM"] = df_grouped["Real_Variacao"].cumsum()
    df_grouped["META_ACUM"] = df_grouped["Meta Dia"].cumsum()

    df_grouped["DESVIO_DIA_R$"] = df_grouped["Real_Variacao"] - df_grouped["Meta Dia"]
    df_grouped["DESVIO_ACUM"] = df_grouped["REAL_ACUM"] - df_grouped["META_ACUM"]

    df_grouped["DESVIO_DIA_PCT"] = (
        df_grouped["DESVIO_DIA_R$"] /
        df_grouped["Meta Dia"].replace(0, np.nan) * 100
    ).fillna(0)

    df_grouped["DESVIO_ACUM_PCT"] = (
        df_grouped["DESVIO_ACUM"] /
        df_grouped["META_ACUM"].replace(0, np.nan) * 100
    ).fillna(0)

    return df_grouped

def aplicar_estilo(fig):
    fig.update_layout(
        template="plotly_white",
        autosize=True,
        dragmode=False,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1,
            xanchor="left",
            x=0
        ),
        margin=dict(l=10, r=10, t=120, b=10),
        font=dict(size=12)
    )
    fig.update_xaxes(tickangle=30)
    return fig

# ------------------------------------------------------
# FUNÇÃO GRÁFICOS 2x2
# ------------------------------------------------------
def plot_2x2(df_grouped, produto, mes, ano):
    st.subheader(f"{produto} — {mes}/{ano}")

    first_day = pd.Timestamp(year=ano, month=mes, day=1)
    last_day = first_day + pd.offsets.MonthEnd(0)

    full_dates = pd.DataFrame({"Data": pd.date_range(first_day, last_day)})
    df = full_dates.merge(df_grouped, on="Data", how="left")
    df["DataLabel"] = df["Data"].dt.strftime("%d/%m")

    df = df[~(df["Real_Variacao"].isna() & df["Meta Dia"].isna())]

    modo = st.radio(
        "Selecione a visualização:",
        ["Diário", "Acumulado"],
        horizontal=True
    )

    if modo == "Diário":
        fig1 = go.Figure()
        fig1.add_bar(
            x=df["DataLabel"],
            y=df["Real_Variacao"],
            name="Real Dia",
            marker_color="#EA9411"
        )
        fig1.add_scatter(
            x=df["DataLabel"],
            y=df["Meta Dia"],
            mode="lines+markers",
            name="Meta Dia",
            marker=dict(color="blue")
        )
        st.plotly_chart(aplicar_estilo(fig1), use_container_width=True)

        fig2 = go.Figure()
        fig2.add_bar(
            x=df["DataLabel"],
            y=df["DESVIO_DIA_R$"],
            marker_color=[
                "#EA9411" if x >= 0 else "gray"
                for x in df["DESVIO_DIA_R$"]
            ]
        )
        fig2.add_hline(y=0)
        st.plotly_chart(aplicar_estilo(fig2), use_container_width=True)

    else:
        fig3 = go.Figure()
        fig3.add_bar(
            x=df["DataLabel"],
            y=df["REAL_ACUM"],
            marker_color="#EA9411"
        )
        fig3.add_scatter(
            x=df["DataLabel"],
            y=df["META_ACUM"],
            mode="lines+markers",
            marker=dict(color="blue")
        )
        st.plotly_chart(aplicar_estilo(fig3), use_container_width=True)

        fig4 = go.Figure()
        fig4.add_bar(
            x=df["DataLabel"],
            y=df["DESVIO_ACUM"],
            marker_color=[
                "#EA9411" if x >= 0 else "gray"
                for x in df["DESVIO_ACUM"]
            ]
        )
        fig4.add_hline(y=0)
        st.plotly_chart(aplicar_estilo(fig4), use_container_width=True)

# ------------------------------------------------------
# PÁGINA — PRODUÇÃO
# ------------------------------------------------------
if pagina == "Produção":
    st.header("Produção")

    st.sidebar.header("Filtros")

    produto_sel = st.sidebar.selectbox(
        "Produto",
        ["Todos"] + sorted(rede["Produto"].dropna().unique())
    )

    regional_sel = st.sidebar.selectbox(
        "Regional",
        ["Todas"] + sorted(rede["Regional"].dropna().unique())
    )

    df_tmp = rede if regional_sel == "Todas" else rede[rede["Regional"] == regional_sel]

    coordenador_sel = st.sidebar.selectbox(
        "Coordenador",
        ["Todos"] + sorted(df_tmp["Coordenador"].dropna().unique())
    )

    df_tmp = df_tmp if coordenador_sel == "Todos" else df_tmp[df_tmp["Coordenador"] == coordenador_sel]

    loja_sel = st.sidebar.selectbox(
        "Loja",
        ["Todas"] + sorted(df_tmp["Nome_Loja"].dropna().unique())
    )

    anos = sorted(rede["Data"].dt.year.unique())
    meses = sorted(rede["Data"].dt.month.unique())

    ano_sel = st.sidebar.selectbox("Ano", anos, index=len(anos) - 1)
    mes_sel = st.sidebar.selectbox("Mês", meses)

    df_f = filtrar_df(
        rede,
        produto_sel,
        regional_sel,
        coordenador_sel,
        loja_sel,
        mes_sel,
        ano_sel
    )

    if df_f.empty:
        st.warning("Nenhum dado após aplicar os filtros.")
        st.stop()

    df_grouped = calcular_acumulados(df_f)
    plot_2x2(df_grouped, produto_sel, mes_sel, ano_sel)

    st.subheader("Tabela Consolidada")

    df_exibir = df_grouped.copy()
    df_exibir["Produção Dia"] = df_grouped["Real_Variacao"].apply(format_large_numbers)
    df_exibir["Meta Dia"] = df_grouped["Meta Dia"].apply(format_large_numbers)
    df_exibir["Produção Acumulada"] = df_grouped["REAL_ACUM"].apply(format_large_numbers)
    df_exibir["Meta Acumulada"] = df_grouped["META_ACUM"].apply(format_large_numbers)
    df_exibir["Desvio Dia"] = df_grouped["DESVIO_DIA_R$"].apply(format_large_numbers)
    df_exibir["Desvio Acumulado"] = df_grouped["DESVIO_ACUM"].apply(format_large_numbers)

    df_exibir = df_exibir[[
        "Data",
        "Produção Dia",
        "Meta Dia",
        "Desvio Dia",
        "Produção Acumulada",
        "Meta Acumulada",
        "Desvio Acumulado"
    ]]

    st.dataframe(df_exibir, use_container_width=True)

    buffer = io.BytesIO()
    df_exibir.to_excel(buffer, index=False, engine="openpyxl")
    buffer.seek(0)

    st.download_button(
        "Baixar tabela em Excel",
        buffer,
        f"consolidado_{mes_sel}_{ano_sel}.xlsx",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
